language: R
sudo: false
cache: packages

notifications:
  email: false
  slack:
    secure: hGK7ukf6Zuijxo6cy90J34nGS0vwjeCedCrD5KnR7nWpMI5ltT98tuPN1nzhQgRVVjqAAPwWQVIOT0Oq4OHsfTKTaSjDTNlxIF5BuTLRR8V0tUPmXMyMu2HWhLKUH1Ii4NrXTZGiEGZ8kjkBGoS9gkbstWCPwZtGCakVqRSJ+u6lGKIBUIkH4TkgdK4WTFTmhPw+YoLWAyOfV1+FD9q+w40LBSVwniAfmTN86PlYJDUz/Czgenxd/Bx1TFKNQhMCXd2tzJTmzm+9ansXTRZd/CIRP1Bju9PRdD2IfiZr6c/BBz8drY6Fg1JJdbc6in3wQZvQgUB06c/VERDeaKCRP4uQmdx3nCQ8yNrJXzZw8WIlqCJT51m7666neqIS6k8sx0GYJvcZeC2c3x6u51upC3B2g6SXNMoW+OmLHQ6++8SHDqNoexYXESMW/qQOQEkS68lYTJWOJ8uIRFFVUcQ06VTHPaQAGxPnaCJvhmvWMUdhLaADfBg/k7gOmPzxj1a1I55XyLg0OsolFu2MtKZftA8fttHlgJWauoQx/6EcP+nm+t0iRV3NQHDoOa2Et1KJt82i44LWau0o0ufFOfvc/hAGx72XsM3XHMpjlpue9lNrY/7OdLgivmrylwsBg6FEr9DR6Pv3L8+nscdSCiD/qI2WLMj1RfqrfzCy2F7Co5s=
