language: R
sudo: false
cache: packages
notifications:
  email: false
  slack:
    secure: cG13GUz4C3szTL//TL/vvq+3jyPPkQWYNauf9V2JkpDkoH1JxGl0nhi/gnX0okMKZX7ojSWsziOjayj6P7TEIasCc6gxx/EmdFvs5VHZMNj0kfb1GN9XSrNvZgB3h5qKvWtos/oiuhONKlcNGLocL0n01jTc2sYo1O0WKNo7FI5N9Ia/9d1DPTMIGJ7cORCyZwIIo6aaoB8QsnHzzFzqPRtgLatiiAPeqgi2aueVghSgxAWRNbOvPBVZJde3/iqhVTKhjD9EFg5Po8Yr9vjP4sWJTmcbHFMITRm1yZaVLkXAHKrsfseksLad6AaZY8TxbOmho2YKNefnYbFuyOkUOLrReM4ZxP6PQOHQN3h9eI/V2sRSZj94nsXDfwEWFdNRVJHlgp0uta1t6Ppdx5wIeSeaM89ntKPRloiZQvSNnrrf4fHPlbdDO1EdHIZTwRmcm9ngoEG7q66/uWo+ROm1yuBi40R3TiTNKqrQWs4YpYJBQkhoakD5BlyurKtKm+jnzSjjnz/U0KOzy4U8Ia6vkPHfrXXY4SJs5VsXZZx5YOWLMb88xZObMdGspRnY59XnRHY28clTnPLxfpMpITY4Z6e6cbZxb+Uki4c1bfgKifO6alHAhqthE01NvQTGBIzndfQQ1XXbHLvK5XSj1y33F5yb7ikPaIRwRSsqnhjwlBQ=
